version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=DB
    ports:
      - '5432:5432'
    networks:
      - app-tier
    volumes:
      - ./db:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  api:
    platform: linux/amd64
    depends_on:
      - db
    networks:
      - app-tier
    build:
      context: ./
      dockerfile: ./Dockerfile

volumes:
  db:
    driver: local

networks:
  app-tier:
    driver: bridge