version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${HOST_PORT}:${CONTAINER_PORT}'
    networks:
      - app-tier
    volumes:
      - ./db:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  api:
    platform: linux/amd64
    depends_on:
      - db
    networks:
      - app-tier
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - HOST_PORT:${HOST_PORT}
    build:
      context: ./
      dockerfile: ./Dockerfile

volumes:
  db:
    driver: local

networks:
  app-tier:
    driver: bridge